[tool.black]
line-length = 88
target-version = ["py312"]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "DJ"]
extend-select = ["I"]
per-file-ignores = { "__init__.py" = ["F401"] }

[tool.ruff.per-file-ignores]
"**/migrations/*.py" = ["E501"]
"**/settings.py" = ["E501"]